### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by yiqiaoqingyuyu** [NVlabs/FoundationPose#267]
Hello, author. Thank you very much for your work. I encountered an issue when running the demo data. Everything works fine when running the mustard0 sequence, but when I switch to the kinect_driller_seq, I get the error torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 886.00 MiB. I understand that this is caused by insufficient GPU memory. I followed the solution for a similar, already closed issue, and used Blender to reduce the number of mesh points in the textured_mesh.obj file under the mesh folder. I even scaled it down to the smallest possible ratio, reducing the file size from 8.5MB to 173KB. However, the CUDA out-of-memory error persists. Could you suggest any other modifications I can try to resolve this issue?

My GPU is an RTX 3060 with 12GB of VRAM.
Thank you in advance for your help, and I look forward to your reply.

**Comment by wenbowen123** [comment]
it maybe because the image resolution is higher in kinect data. You can downsize the shorter_side [here](https://github.com/NVlabs/FoundationPose/blob/main/run_demo.py#L44)

**Comment by yiqiaoqingyuyu** [comment]
> it maybe because the image resolution is higher in kinect data. You can downsize the shorter_side [here](https://github.com/NVlabs/FoundationPose/blob/main/run_demo.py#L44)

Thanks!!! Fixing the parameter did the trick. I totally missed that—really appreciate your help! Thanks again!!!
