### ISSUE TITLE
RuntimeError: Cuda error: 2[cudaMalloc(&m_gpuPtr, bytes);]`

### ISSUE THREAD

**Issue by ethanshenze** [NVlabs/FoundationPose#43]
When I used the pictures taken by realsense d435i to test, I encountered such an error. I couldn't find the reason. What is the cause of this problem? (I just replaced the data in the mustard0 folder with my own data)   

error like this:
`[register()] Welcome
Module Utils load on device 'cuda:0' took 144.14 ms
[register()] poses:(252, 4, 4)
[register()] after viewpoint, add_errs min:-1.0
/opt/conda/envs/my/lib/python3.8/site-packages/torch/__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] trans_normalizer:[0.019999999552965164, 0.019999999552965164, 0.05000000074505806], rot_normalizer:0.3490658503988659
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
RuntimeError: Cuda error: 2[cudaMalloc(&m_gpuPtr, bytes);]`

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/FoundationPose/issues/25#issuecomment-2037719050
can you try the suggestions there?

It's likely your data is not formatted correctly.

**Comment by rorrewang** [comment]
Hi @ethanshenze  , I get same error output like this when running it on my custom dataset and looking forward to some help. Have you solved it?Thanks!

By the way ,I have checked the debug_folder and it looks OK.

**Comment by wenbowen123** [comment]
the error maybe due to OOM. What's your GPU memory? @rorrewang

**Comment by rorrewang** [comment]
@wenbowen123  I just solved this problem. I was so stupid that I forget to check my mesh model size and GPU memory is not enough.I changed my mesh model size from 16mb to 2mb and it works. Thank you for your help :)
